require("colorscheme")
-- 插件配置
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.lualine")
-- 内置LSP (新增)
require("lsp.setup")
require("lsp.cmp")
require("plugin-config.nvim-treesitter")
